### PR TITLE
don't include old packages in the .tgz

### PR DESCRIPTION
**Pull request by joscol**
The tarball for version 0.4.1 was huge because it included several old builds.  More aggressive cleaning may be needed in the future, but this should work for now.

### CODE REVIEW

**Comment by vtbassmatt** [comment]
Hmm, for whatever reason, those bogus .tgzs [don't seem to exist in CI](https://dev.azure.com/mseng/PipelineTools/_build/results?buildId=7925156&view=logs&jobId=7702c57f-255d-503a-6154-966e1cf43557&taskId=496f4549-f787-5859-fa68-317e5515de87&lineStart=25&lineEnd=25&colStart=1&colEnd=66).

**Comment by joscol** [comment]
> Hmm, for whatever reason, those bogus .tgzs don't seem to exist in CI.

It starts from a clean slate on the build machine.  I'm trying figure out how to make deleting a file that doesn't exist not fail...

**Comment by vtbassmatt** [comment]
`shx -e` I think.

**Comment by vtbassmatt** [comment]
Also, if CI is able to build it cleanly, that might be good enough. Since we should only be shipping CI system outputs, not dev machine builds, right? :wink:

**Comment by joscol** [comment]
> `shx -e` I think.

Nope, `-e` isn't supported by `rm`, but looking through https://github.com/shelljs/shelljs/blob/master/src/rm.js is looks like `-f` (force) will suppress the error, oddly.

**Pull request merged**
